### ISSUE TITLE
Alpha Centauri - Animation performance issue

### ISSUE THREAD

**Issue by vv221** [libsdl-org/sdl12-compat#277]
Alpha Centauri used to be provided with a native engine developed by Loki, that can still be used with ./play.it (using the game build sold on GOG as a basis): https://www.dotslashplay.it/en/games/alpha-centauri

One of the differences I noticed when using the sdl12-compat wrapper instead of real SDL 1.2 is that the initial animation of the pod landing is very sluggish, while it is smooth with the old SDL 1.2 library.

Since this would require access to a commercial game for investigating the issue, I would be OK to buy a gift code to someone willing to work on this issue but does not own a copy of the game yet.

I am of course willing to provide more information, but since I’m quite new to anything related to SDL I would need step-by-step instructions on how to debug the issue.

**Comment by icculus** [comment]
I have a copy of Loki's Alpha Centauri somewhere, so I can look into this.

**Comment by vv221** [comment]
The build I tested has a slight difference with the out-of-the-box Loki version: to avoid the requirement on [old compatibility libraries](http://www.improbability.net/loki/), a small shim is preloaded that allows it to run on top of current libraries.

Here is a copy of the shim:
```c
#define _GNU_SOURCE

#include <stdio.h>
#include <stdlib.h>

void *__builtin_new(size_t size)
{
    return malloc(size);
}

void __builtin_delete(void *ptr)
{
    free(ptr);
}

void *__builtin_vec_new(size_t size)
{
    return malloc(size);
}

void __builtin_vec_delete(void *ptr)
{
    free(ptr);
}
```
And its source: https://github.com/ZeroPointEnergy/smacshim

**Comment by vv221** [comment]
Extra detail that might be useful: I am running the game on an up-to-date Debian Sid, providing sdl12-compat **1.2.60** and SDL 2 **2.26.0**.

**Comment by icculus** [comment]
Did this get fixed by #278 or #279?

**Comment by vv221** [comment]
> Did this get fixed by https://github.com/libsdl-org/sdl12-compat/issues/278 or https://github.com/libsdl-org/sdl12-compat/issues/279?

No, I still get sluggish animation for the initial pod landing when building from the current HEAD of main (commit b2f7b7736b4adaba2805e5d2979c51676ee950ce).

I suspect it might be an issue with all animations, but is noticeable only with this one because other animations in this game are very short.

**Comment by vv221** [comment]
I can not say with precision when it has been fixed, but I no longer get any noticeable performance problem with animations.
