### ISSUE TITLE
issues affecting Loki port of Sim City 3000

### ISSUE THREAD

**Issue by twolife** [libsdl-org/sdl12-compat#339]
I know that this is borderline "out-of-scope", as that game is an ancient SDL 1.1 game unplayable with a modern glibc without using some nasty hack like https://github.com/twolife/sc3u-nptl, but here it is, I'm running this game on a modern stack (including sdl12-compat) and it almost works perfectly :-) 

The first issue is that the intro movie is flickering. I'm surprised as I saw issue #49 that was resolved, but the intro movie in SC3U is still affected.

<details>
  <summary>Second issue is that the game segfault on exit</summary>

  ```
BUG! (Segmentation Fault)  Going down hard...
SimCity 3000 Unlimited 2.0.955a
Built with glibc-2.1 on x86
Stack dump:
{
	0x83fc566
	0xf66693b7
	0xf6669e01
	0xf664dba4
	0xf66b5a49
	0xf7f38e41
	0xf7936086
}
Please send a full bug report,
along with the contents of autosave to: support@lokigames.com
Unable to execute loki_qagent - exiting
  ```
</details>

Those are very minor issues, but this is not happening with a real SDL-1.2, so i suppose it's a bug #sorry

Anyway, this is at least documented now.

**Comment by icculus** [comment]
> #sorry

We definitely fixed other issues in other Loki binaries, so this is 100% in scope, fwiw.

**Comment by terinjokes** [comment]
```
Thread 1 "sc3u.dynamic" received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in ?? ()
#1  0xf7df0cb3 in SDL_DestroyMutex (a=0x865d4d0) at /var/tmp/portage/media-libs/libsdl-1.2.68/work/sdl12-compat-release-1.2.68/src/SDL20_syms.h:179
#2  0x083fc566 in _._18cRZCriticalSection ()
#3  0xf6c223b7 in ?? () from /home/terin/SC3U/lib/libAudio.so
#4  0xf6c22e01 in ?? () from /home/terin/SC3U/lib/libAudio.so
#5  0xf6c06ba4 in ?? () from /home/terin/SC3U/lib/libAudio.so
#6  0xf6c6ea49 in _fini () from /home/terin/SC3U/lib/libAudio.so
#7  0xf7fcc2e9 in _dl_fini () at dl-fini.c:114
#8  0xf799ff4a in ?? () from /usr/lib/libc.so.6
#9  0xf79a0143 in exit () from /usr/lib/libc.so.6
#10 0xf798604f in ?? () from /usr/lib/libc.so.6
#11 0xf7986108 in __libc_start_main () from /usr/lib/libc.so.6
#12 0x08135901 in _start ()
```

I see the `_fini` for libsdl and libsdl2 have already been called at this point, so if I'm reading this correctly, the code is trying to destroy a mutex after SDL2 has been unloaded?

**Comment by icculus** [comment]
This should be fixed by #360.

**Comment by Gymnasiast** [comment]
@icculus 
https://github.com/libsdl-org/sdl12-compat/pull/360 only fixed the segfault - the flickering intro issue is still present as of `45fb7be084c477b5d6b0df53f3e93200abd51f40`. 

Would you like me to open a new issue for that, or would you prefer reopening this one?

**Comment by icculus** [comment]
I opened one for it; thanks for letting me know!
