### ISSUE TITLE
Mouse regression of v1.2.68 with ETQW

### ISSUE THREAD

**Issue by rea987** [libsdl-org/sdl12-compat#370]
Might be related with https://github.com/libsdl-org/sdl12-compat/issues/368 and/or https://github.com/libsdl-org/sdl12-compat/issues/367 .

Enemy Territory: Quake Wars full game and demo version cannot grab mouse, hence there is no mouse movement when sdl12-compat v1.2.68 is used; default sdl1.2, sdl-compat v1.2.60 had no such issue.

Worth mentioning, sdl12-compat incorporated id Tech 4 patch for ETQW and Quake 4; https://github.com/libsdl-org/sdl12-compat/issues/7 .

For Arch based distros, please check the following guide to avoid library dependecy issues and better compatibility.

- Backup and delete the following libs from the game's directory: `libgcc_s.so.1`, `libjpeg.so.62`, libstdc++.so.6`
- Install the following packages from Arch repos: ~~`lib32-sdl12-compat`~~, `lib32-libjpeg6-turbo`, `lib32-pipewire`, `lib32-alsa-lib`
- Edit `~/.etqwcl/base/etqwconfig.cfg` > Find and edit *s_micDevice* line > `seta s_micDevice "pipewire"`
- Launch the game with **etqw-rthread** script.

**Comment by smcv** [comment]
As a data point, Arch is using sdl2-compat, so the stack is:

game → sdl12-compat → sdl2-compat → SDL3 → (lower-level stuff)

and it's possible that "classic" SDL2:

game → sdl12-compat → SDL2 → (lower-level stuff)

would have a different result. (Debian testing/unstable or Ubuntu could be a convenient way to try that.)

**Comment by rea987** [comment]
@smcv It turned out that you are correct.

- lib32-sdl12-compat 1.2.68-2 on Manjaro Cinnamon 25.0.3 cannot grab the mouse of ETQW.

- libsdl1.2-compat:i386 1.2.68-2 on Ubuntu Mate 24.04.3 can  grab the mouse of ETQW.

So, is that a SDL3 and/or Arch issue?

**Comment by smcv** [comment]
> So, is that a SDL3 and/or Arch issue?

It's only an Arch issue to the extent that Arch has chosen to replace "classic" SDL2 with sdl2-compat, even if sdl2-compat might not be 100% ready yet. (Fedora has done the same transition, and I want to do the same in Debian at some point, but we're not there yet.)

Ideally sdl2-compat would be accurately emulating the behaviour of "classic" SDL2 (possibly by telling SDL3 to behave differently), so it could be considered to be a sdl2-compat issue. Or perhaps SDL3 is not behaving in the ideal way and should just be fixed, in which case it could be a SDL3 issue.

Another thing that might be different is that if you're in a Wayland desktop environment, "classic" SDL2 defaults to using X11 for video/keyboard/mouse (via Xwayland), whereas sdl2-compat often defaults to native Wayland. But I don't think Cinnamon supports Wayland yet, so probably your Manjaro Cinnamon session is native X11 using Xorg, and SDL has no choice but to use X11 anyway?

**Comment by Kontrabant** [comment]
> I don't think Cinnamon supports Wayland yet

It has Wayland support being worked on, but the last time I tried it (several months ago while investigating another bug report), it was in very rough shape, and relative pointer mode didn't work at all. It's worth making sure that it's running in X11 mode to rule that out.

**Comment by rea987** [comment]
> It's only an Arch issue to the extent that Arch has chosen to replace "classic" SDL2 with sdl2-compat, even if sdl2-compat might not be 100% ready yet.

That's seriously bad. Because, SteamOS 3+ is based on Arch. Any attempt to make a native SDL1.2 game run on SteamOS and/or Steam Deck via sdl12-compat will result this issue.

So, what now? Reverting sdl2-compat on Arch based distros manually?

**Comment by smcv** [comment]
On SteamOS and the Steam Deck, Steam games use a compatibility tool (the various branches of the Steam Linux Runtime) to insulate games from the fast-moving OS. Non-Steam game shortcuts can also be configured to run under a compatibility tool (and if the game is so old that it uses SDL 1.2, then running it under a compatibility tool is probably a good idea).

The Steam Linux Runtime will also switch to sdl2-compat as its default at some point, when sdl2-compat seems sufficiently ready (it already has sdl2-compat available as a non-default option), but the plan is to keep "classic" SDL 2 around for a while and have a mechanism to switch back to it on a per-game basis if needed.

Like I said, ideally sdl2-compat would mimic the behaviour of "classic" SDL 2 in all of the ways that matter. If it doesn't, then that's a bug.

> Any attempt to make a native SDL1.2 game run

Do you know this to be true? Based on the information available here so far, this could equally well be specific to this one game (or perhaps the idTech 4 engine that it shares with Doom 3 and Quake 4).

**Comment by rea987** [comment]
> Based on the information available here so far, this could equally well be specific to this one game (or perhaps the idTech 4 engine that it shares with Doom 3 and Quake 4).

Good point. Let me try couple more id Tech 4 games (Quake 4, Prey 2006) and an Unreal Engine 2 game (UT2004). Any game suggestions?

**Comment by Kontrabant** [comment]
Following the steps you listed in the original post, the game was still loading the included `libSDL-1.2.id.so.0` file, that is the real (modified) SDL-1.2 it ships with, and mouse grabbing is broken on Fedora 42 with GNOME as well. If I remove that file and replace it with a symlink to the system's sdl12-compat, then mouse grabbing works correctly, mouse motion feels smoother since it's using the raw motion from SDL2/SDL3, but running under sdl12-compat->sdl2-compat->SDL3, rendering in the game is broken:

X11:
<img width="5120" height="2880" alt="Image" src="https://github.com/user-attachments/assets/090f556a-8e94-4981-ac74-95e4f7728d6d" />

Wayland:
<img width="5120" height="2880" alt="Image" src="https://github.com/user-attachments/assets/13e4f454-6f55-49ca-b43b-f4dce23f9984" />

The logs are filled with things such as:
```
WARNING: GL_PROGRAM_ERROR_STRING_ARB: 
GL_PROGRAM_ERROR_POSITION_ARB < 0 with error
WARNING: idDeclLocal::ParseLocal Failed to Parse decl 'trivialrgb' in file 'renderprogs/trivial.rprog' line 0
WARNING: sdDeclRenderProgram::ResolveReferences : Reference shader of type 1 is defaulted in 'trivialrgbwithtexturematrix'
WARNING: idDeclLocal::ParseLocal Failed to Parse decl 'trivialrgbwithtexturematrix' in file 'renderprogs/trivial.rprog' line 0
WARNING: file materials/shaderdemo.mtr: wipe2material, line 0: Unable to parse render program 'trivialRGBWithTextureMatrix'
WARNING: idDeclLocal::ParseLocal Failed to Parse decl 'wipe2material' in file 'materials/shaderdemo.mtr' line 0
```

This is on the proprietary NVIDIA driver. Reverting to the real SDL 1.2 fixes it, but then mouse grabbing is broken again.

**Comment by Kontrabant** [comment]
Ah, the game uses Nvidia's cg library for shader compilation, so Wayland isn't expected to work, since cg presumes that it is always on GLX, but why switching to sdl12-compat causes transparent textures on X11 to be solid black is puzzling.

**Comment by smcv** [comment]
> Ah, the game uses Nvidia's cg library for shader compilation, so Wayland isn't expected to work

I thought we had a workaround that detected use of Cg and turned off native Wayland, is that not working here?

Adding `etqw.x86` and `etqw-rthread.x86` to the quirks table might be helpful; perhaps also `quake4.x86` and `quake4smp.x86`.

**Comment by smcv** [comment]
> Following the steps you listed in the original post, the game was still loading the included `libSDL-1.2.id.so.0` file, that is the real (modified) SDL-1.2 it ships with

@rea987, are you absolutely sure that when you reported this issue, the game in the configuration you were using was genuinely loading sdl12-compat? See: https://github.com/libsdl-org/sdl12-compat/blob/main/HOW_TO_TEST_GAMES.md#am-i-actually-running-sdl12-compat

If your host system is using sdl2-compat to implement "classic" SDL2 (like Arch does), then also export `SDL2COMPAT_DEBUG_LOGGING=1` - that will confirm that the SDL2 that you think was loaded is actually being loaded.

**Comment by smcv** [comment]
> why switching to sdl12-compat causes transparent textures on X11 to be solid black is puzzling

That sounds like maybe something to turn into a separate issue report, with details of the system where it was seen.

**Comment by Kontrabant** [comment]
Opened #372 for the transparent texture issue.

**Comment by rea987** [comment]
My Manjaro system that uses X11:

https://gist.github.com/rea987/36bab9514b1c5bd6b71015f5ad61acf9

@Kontrabant That's odd. On Manjaro Cinnamon 25.0.3 which utilizes lib32-sdl12-compat > lib32-sdl2-compat > lib32-sdl3, using the game's original `libSDL-1.2.id.so.0` makes the game grab mouse and render the game, linking lib32-sdl12-compat's .so as `libSDL-1.2.id.so.0` breaks the mouse grabbing and rendering.

https://github.com/libsdl-org/sdl12-compat/issues/372 This issue is not Nvidia specific; it also happens on AMD with Mesa drivers when the game uses lib32-sdl12-compat.

@smcv  

etqw SDL12COMPAT_DEBUG_LOGGING=1 https://gist.github.com/rea987/795c8812685d5e4e75486489993811c9
etqw SDL2COMPAT_DEBUG_LOGGING=1 https://gist.github.com/rea987/2534fc3ac2b6f479196f26e636d17725
etqw SDL_EVENT_LOGGING=1 https://gist.github.com/rea987/f515d3029f092586c0a97cb9ca617c05

Worth noting that when the game's original custom sdl12 lib is used, the game's own mouse cursor appears, when sdl12-compat is used, the OS' mouse cursor appears.

As I mentioned in https://github.com/libsdl-org/sdl12-compat/issues/370#issue-3484725093 , @icculus ported id Tech 4 patch for Quake 4 and ETQW into sdl12-compat previously; https://github.com/libsdl-org/sdl12-compat/issues/7 . This patch might be needed to be ported over to sdl2-compat and/or sdl3. Though, I haven't found time to test more id Tech 4 games (Quake 4, Prey 2006) and an Unreal Engine 2 game (UT2004).

**Comment by rea987** [comment]
Just tried another id Tech 4 game, Prey (2006) retail and Prey (2006) demo version on the same system.

https://icculus.org/prey/

Mouse grabbing failure is identical.

- The game's stock libSDL-1.2.so.0 functions just fine (albeit no alt+tab support etc)
- Linking Manjaro's (Arch) sdl12-compat as libSDL-1.2.so.0 and running the game with sdl12-compat > sdl2-compat > sdl3 setup results the same failure to grabbing the mouse issue. Unlike ETQW, the mouse cursor changes into the game's mouse cursor with sdl12-compat but doesn't work nevertheless.
- Unlike ETQW, there is no rendering issues nor in menu, neither in the maps (load them via console as the mouse in unavailable; map /game/<mapname>
- Not sure if the game uses threaded renderer patch, could be reason why there is no rendering issue.

Backup and remove libgcc_s.so.1, libNvidiaVidMemTest.so, libSDL-1.2.so.0, libstdc++.so.5; install lib32-libstdc++5. Additionally, put the following line in ~/.prey-demo/base/preyconfig.cfg to avoid resolution related crashes:

seta r_customHeight "1080"
seta r_customWidth "1920"
seta r_fullscreen "1"
seta r_mode "-1"

**Comment by rea987** [comment]
Quake 4 retail and Quake 4 demo is exactly the same with Prey (2006) regardless of using quake4.x86 or quake4smp.x86.

- Stock libSDL-1.2.id.so.0 works fine.
- sdl12-compat > sdl2-compat > sdl3 is unable to grab mouse.
- No rendering issues with sdl12-compat.

Additionally, similar to ETQW, Quake 4 definitely use SDL patch to enable threaded renderer; sdl.patch.1.2.10

Enabling SMP support via cfg edit didn't affect the rendering.

https://www.quaddicted.com/files/idgames2/idstuff/quake4/linux/
https://www.moddb.com/games/quake-4/downloads/quake-4-linux-demo

**Comment by rea987** [comment]
Unreal Tournament 2004 (x64) has no mouse or rendering issues with sdl12-compat > sdl2-compat > sdl3 setup when linked properly.

https://archive.org/details/ut2004-3369
https://community.pcgamingwiki.com/files/file/164-unreal-tournament-2004-linux-patch/
https://www.pcgamingwiki.com/wiki/Unreal_Tournament_2004#Install_native_Linux_version

**Comment by rea987** [comment]
The original Trine from Humble Bundle has no mouse or rendering issues with sdl12-compat > sdl2-compat > sdl3 setup when linked properly.

It looks like the issue is id Tech 4 specific.

**Comment by icculus** [comment]
Can you make sure the in_nograb cvar isn't set?

**Comment by rea987** [comment]
> Can you make sure the in_nograb cvar isn't set?

@icculus, It is set to 0 as default on ETQW, Prey and Quake 4.

Now, the odd new is none of these id Tech 4 game has any mouse or rendering issues with sdl12-compat on updated Manjaro Cinnamon anymore. I can swear that the issue was there yesterday. The only updated packages are the following:

```
[2025-10-25T15:35:30+0300] [ALPM] upgraded thunderbird (143.0.1-1 -> 144.0-0.1)
[2025-10-25T15:35:30+0300] [ALPM] upgraded manjaro-release (25.0.9-1 -> 25.0.10-1)
[2025-10-25T15:35:20+0300] [ALPM] upgraded archlinux-keyring (20250929-1 -> 20251012-1)
```

The packages installed yesterday are the following:

```
[2025-10-25T17:35:42+0300] [ALPM] installed libx86 (1.1-9)
[2025-10-25T17:32:29+0300] [ALPM] installed lib32-libglade (2.6.4-8)
[2025-10-25T17:32:11+0300] [ALPM] installed libglade (2.6.4-9)
[2025-10-25T17:32:11+0300] [ALPM] installed python2 (2.7.18-12)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-gtk2 (2.24.33-5)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-libxinerama (1.1.5-2)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-libcups (2.4.11-1)
[2025-10-25T17:18:53+0300] [ALPM] installed xterm (402-1)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-at-spi2-core (2.56.4-1)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-libxtst (1.2.5-2)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-libxdamage (1.1.6-2)
[2025-10-25T17:18:53+0300] [ALPM] installed luit (20250912-1)
[2025-10-25T17:18:53+0300] [ALPM] installed libxaw (1.0.16-1)
[2025-10-25T17:18:53+0300] [ALPM] installed xbitmaps (1.1.3-2)
[2025-10-25T17:18:53+0300] [ALPM] installed tk (8.6.16-1)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-libxi (1.8.2-1)
[2025-10-25T17:18:53+0300] [ALPM] installed openssl-1.1 (1.1.1.w-2)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-libxcomposite (0.4.6-2)
[2025-10-25T17:18:53+0300] [ALPM] installed libutempter (1.2.3-1)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-gnutls (3.8.10-1)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-p11-kit (0.25.7-1)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-libtasn1 (4.20.0-1)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-librsvg (2:2.61.1-1)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-pango (1:1.56.4-2)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-libthai (0.1.29-3)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-libdatrie (0.2.13-3)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-fribidi (1.0.16-2)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-harfbuzz (11.5.0-1)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-gdk-pixbuf2 (2.42.12-2)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-cairo (1.18.4-1)
[2025-10-25T17:18:53+0300] [ALPM] installed lib32-pixman (0.46.4-1)
[2025-10-25T17:18:53+0300] [ALPM] installed gdb (16.3-1)
[2025-10-25T17:18:52+0300] [ALPM] installed source-highlight (3.1.9-15)
[2025-10-25T17:18:52+0300] [ALPM] installed gdb-common (16.3-1)
[2025-10-25T17:18:52+0300] [ALPM] installed xorg-server-xvfb (21.1.18-2)
[2025-10-25T17:18:52+0300] [ALPM] installed lib32-libtiff (4.7.1-1)
[2025-10-25T17:18:52+0300] [ALPM] installed tcl (8.6.16-1)
[2025-10-25T17:18:52+0300] [ALPM] installed lib32-nettle (3.10.2-1)
[2025-10-25T17:18:52+0300] [ALPM] installed lib32-gmp (6.3.0-2)
[2025-10-25T17:18:52+0300] [ALPM] installed lib32-libxft (2.3.8-2)
[2025-10-25T17:18:49+0300] [ALPM] installed lib32-fontconfig (2:2.17.1-1)
[2025-10-25T17:18:49+0300] [ALPM] installed lib32-freetype2 (2.14.1-1)
[2025-10-25T17:18:49+0300] [ALPM] installed lib32-libpng (1.6.50-1)
[2025-10-25T17:18:49+0300] [ALPM] installed lib32-libxrandr (1.5.4-1)
[2025-10-25T17:18:49+0300] [ALPM] installed gtk2 (2.24.33-5)
[2025-10-25T12:00:38+0300] [ALPM] installed libstdc++5 (3.3.6-11)
[2025-10-25T12:00:38+0300] [ALPM] installed lib32-libstdc++5 (3.3.6-9)
```

@Kontrabant. can you please check the rendering issue is still there with sdl12-compat?

**Comment by slouken** [comment]
@rea987, so just to confirm, you verified that these games are using the latest code for sdl12-compat -> sdl2-compat -> SDL3, and they're all working now?

You can check this with:
`ls -l /proc/PID/map_files | grep SDL`
where `PID` is the process ID of the running game.

You should see libSDL, libSDL2, and libSDL3 in there if the chaining is working correctly.

**Comment by slouken** [comment]
It's very possible I fixed this in https://github.com/libsdl-org/sdl12-compat/commit/8149d5720abf050ea506fe6ed48eee0e6060bafe

**Comment by Kontrabant** [comment]
> @Kontrabant. can you please check the rendering issue is still there with sdl12-compat?

Unforunately, I can't at the moment; the NVMe drive in my desktop died last week, and it's currently on its way back to the manufacturer for warranty replacement. ETQW won't even start on this old Intel iGPU machine, as it fails with `SDL_SetVideoMode failed: Couldn't find matching GLX visual`.

**Comment by rea987** [comment]
> [@rea987](https://github.com/rea987), so just to confirm, you verified that these games are using the latest code for sdl12-compat -> sdl2-compat -> SDL3, and they're all working now?

@slouken, just did a clean Manjaro Cinnamon 25.0.3 installation, updated the system and installed the following:

```
[2025-10-26T20:32:09+0200] [ALPM] installed lib32-pipewire-v4l2 (1:1.4.8-2)
[2025-10-26T20:32:09+0200] [ALPM] installed lib32-pipewire (1:1.4.8-2)
[2025-10-26T20:32:09+0200] [ALPM] installed lib32-glib2 (2.84.4-2)
[2025-10-26T20:32:09+0200] [ALPM] installed lib32-util-linux (2.41.1-1)
[2025-10-26T20:32:09+0200] [ALPM] installed lib32-dbus (1.16.2-1)
[2025-10-26T20:32:09+0200] [ALPM] installed lib32-alsa-lib (1.2.14-1)
[2025-10-26T20:32:09+0200] [ALPM] installed lib32-libpipewire (1:1.4.8-2)
[2025-10-26T20:32:09+0200] [ALPM] installed pipewire-v4l2 (1:1.4.8-2)
[2025-10-26T20:32:09+0200] [ALPM] installed lib32-pcre2 (10.46-1)
[2025-10-26T20:27:27+0200] [ALPM] installed lib32-sdl12-compat (1.2.68-2)
[2025-10-26T20:27:27+0200] [ALPM] installed lib32-sdl2-compat (2.32.56-1)
[2025-10-26T20:27:27+0200] [ALPM] installed lib32-sdl3 (3.2.20-1)
```

Unable to grab the mouse issue is back. I will proceed with installing the listed packages one by one to replicate the success scenario.

Edit: Also;

```
$  ls -l /proc/3510/map_files | grep SDL
lr-------- 1 r r 64 26 окт 20:48 f7370000-f7381000 -> /usr/lib32/libSDL3.so.0.2.20
lr-------- 1 r r 64 26 окт 20:48 f7381000-f7584000 -> /usr/lib32/libSDL3.so.0.2.20
lr-------- 1 r r 64 26 окт 20:48 f7584000-f761c000 -> /usr/lib32/libSDL3.so.0.2.20
lr-------- 1 r r 64 26 окт 20:48 f761c000-f7622000 -> /usr/lib32/libSDL3.so.0.2.20
lr-------- 1 r r 64 26 окт 20:48 f7622000-f7629000 -> /usr/lib32/libSDL3.so.0.2.20
lr-------- 1 r r 64 26 окт 20:48 f762e000-f7639000 -> /usr/lib32/libSDL2-2.0.so.0.3200.56
lr-------- 1 r r 64 26 окт 20:48 f7639000-f7672000 -> /usr/lib32/libSDL2-2.0.so.0.3200.56
lr-------- 1 r r 64 26 окт 20:48 f7672000-f7693000 -> /usr/lib32/libSDL2-2.0.so.0.3200.56
lr-------- 1 r r 64 26 окт 20:48 f7693000-f7694000 -> /usr/lib32/libSDL2-2.0.so.0.3200.56
lr-------- 1 r r 64 26 окт 20:48 f7694000-f7695000 -> /usr/lib32/libSDL2-2.0.so.0.3200.56
lr-------- 1 r r 64 26 окт 20:48 f7cb7000-f7cba000 -> /usr/lib32/libSDL-1.2.so.1.2.68
lr-------- 1 r r 64 26 окт 20:48 f7cba000-f7cd5000 -> /usr/lib32/libSDL-1.2.so.1.2.68
lr-------- 1 r r 64 26 окт 20:48 f7cd5000-f7ce4000 -> /usr/lib32/libSDL-1.2.so.1.2.68
lr-------- 1 r r 64 26 окт 20:48 f7ce4000-f7ce5000 -> /usr/lib32/libSDL-1.2.so.1.2.68
lr-------- 1 r r 64 26 окт 20:48 f7ce5000-f7ce6000 -> /usr/lib32/libSDL-1.2.so.1.2.68
```

**Comment by slouken** [comment]
Right, so now grab sdl12-compat, sdl2-compat and SDL3 and build them all from main source (github checkout). I'm guessing that the updated sdl12-compat will work.

**Comment by rea987** [comment]
@slouken, as weird as it sounds, installing **lib32-gtk2** and its dependencies re-fixed the issue on Manjaro Cinnamon 25.0.3 (x11). I haven't grabbed or compiled the latest SDL you suggested, just using sdl12-compat, sdl2-compat, and sdl3 on Arch repos. Not sure if that's DE related; I will test with Gnome 3 and KDE. I am still puzzled with id Tech 4's gtk2 requirement.

```
[2025-10-26T20:56:16+0200] [ALPM] installed lib32-gtk2 (2.24.33-5)
[2025-10-26T20:56:16+0200] [ALPM] installed lib32-libxrandr (1.5.4-1)
[2025-10-26T20:56:16+0200] [ALPM] installed lib32-libxdamage (1.1.6-2)
[2025-10-26T20:56:16+0200] [ALPM] installed lib32-at-spi2-core (2.56.4-1)
[2025-10-26T20:56:16+0200] [ALPM] installed gtk2 (2.24.33-5)
[2025-10-26T20:56:15+0200] [ALPM] installed lib32-libxinerama (1.1.5-2)
[2025-10-26T20:56:15+0200] [ALPM] installed lib32-libcups (2.4.11-1)
[2025-10-26T20:56:15+0200] [ALPM] installed lib32-gnutls (3.8.10-1)
[2025-10-26T20:56:15+0200] [ALPM] installed lib32-nettle (3.10.2-1)
[2025-10-26T20:56:15+0200] [ALPM] installed lib32-gmp (6.3.0-2)
[2025-10-26T20:56:15+0200] [ALPM] installed lib32-p11-kit (0.25.7-1)
[2025-10-26T20:56:15+0200] [ALPM] installed lib32-libtasn1 (4.20.0-1)
[2025-10-26T20:56:15+0200] [ALPM] installed lib32-librsvg (2:2.61.1-1)
[2025-10-26T20:56:15+0200] [ALPM] installed lib32-pango (1:1.56.4-2)
[2025-10-26T20:56:15+0200] [ALPM] installed lib32-libxft (2.3.8-2)
[2025-10-26T20:56:15+0200] [ALPM] installed lib32-fribidi (1.0.16-2)
[2025-10-26T20:56:15+0200] [ALPM] installed lib32-harfbuzz (11.5.0-1)
[2025-10-26T20:56:15+0200] [ALPM] installed lib32-gdk-pixbuf2 (2.42.12-2)
[2025-10-26T20:56:15+0200] [ALPM] installed lib32-libtiff (4.7.1-1)
[2025-10-26T20:56:15+0200] [ALPM] installed lib32-cairo (1.18.4-1)
[2025-10-26T20:56:15+0200] [ALPM] installed lib32-pixman (0.46.4-1)
[2025-10-26T20:56:13+0200] [ALPM] installed lib32-fontconfig (2:2.17.1-1)
[2025-10-26T20:56:13+0200] [ALPM] installed lib32-freetype2 (2.14.1-1)
[2025-10-26T20:56:13+0200] [ALPM] installed lib32-libpng (1.6.50-1)
[2025-10-26T20:56:13+0200] [ALPM] installed lib32-libxcomposite (0.4.6-2)
[2025-10-26T20:56:13+0200] [ALPM] installed lib32-libxtst (1.2.5-2)
[2025-10-26T20:56:13+0200] [ALPM] installed lib32-libxi (1.8.2-1)
[2025-10-26T20:56:13+0200] [ALPM] installed lib32-libjpeg-turbo (3.1.2-1)
[2025-10-26T20:56:13+0200] [ALPM] installed lib32-libthai (0.1.29-3)
[2025-10-26T20:56:13+0200] [ALPM] installed lib32-libdatrie (0.2.13-3)
```

**Comment by slouken** [comment]
Oh, interesting. Yes, you need libxi for correct relative mouse support, which gtk2 pulls in as a dependency. I'm surprised the packaging for SDL doesn't have a dependency on it, but that's a distribution issue, not a problem with SDL.

Thanks for the confirmation!

**Comment by smcv** [comment]
> Yes, you need libxi for correct relative mouse support, which gtk2 pulls in as a dependency. I'm surprised the packaging for SDL doesn't have a dependency on it

This is probably because SDL dlopens it dynamically at runtime (soft dependency), instead of having an ELF DT_NEEDED header (hard dependency) like GTK does.

For SDL 3, the addition of ELF dlopen notes in the format recommended by the systemd team (libsdl-org/SDL#12971, new in 3.3.x) should solve this, but only for distros that parse those notes (the Debian packaging that I maintain does, I assume Fedora also does since the format originated from there, but I'm not sure about other distros).
