### ISSUE TITLE
Flickering in SimCity 3000

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdl12-compat#386]
> @icculus 
https://github.com/libsdl-org/sdl12-compat/pull/360 only fixed the segfault - the flickering intro issue is still present as of 45fb7be084c477b5d6b0df53f3e93200abd51f40.

_Originally posted by @Gymnasiast in https://github.com/libsdl-org/sdl12-compat/issues/339#issuecomment-3591539437_

**Comment by slouken** [comment]
@icculus, is this fixed in the latest code?

**Comment by icculus** [comment]
As far as I know it's still an issue, but I have not tried to reproduce it at this point.

**Comment by twolife** [comment]
OK I got a "fix" for this, but as I don't pretend to even remotely understand the underlying `SDL_PumpEvents()` machinery, my hack has very likely side effects I don't know about :confused:
I did found out, with _printf based debugging_ ©, that there was sometime 2 `PresentScreen()` calls for one YUV frame, one from `SDL_Delay()` and one from `SDL_PumpEvents()`.

`PresentScreen()` calls `SDL_PumpEvents()` and my hack prevent `SDL_PumpEvents()` from calling `PresentScreen()` again:

```diff
--- a/src/SDL12_compat.c
+++ b/src/SDL12_compat.c
@@ -7264,6 +7264,12 @@ PresentScreen(void)
         return;
     }
 
+    /* We're going to present this frame.
+     *
+     * Clear this before SDL_PumpEvents(), otherwise PumpEvents can recursively call PresentScreen().
+     */
+    VideoSurfacePresentTicks = 0;
+
     /* We don't actually implement an event thread in sdl12-compat, but some
      * games will only call SDL_PeepEvents(), which doesn't otherwise pump
      * events, and get stuck when they've consumed all the events.
@@ -7298,7 +7304,6 @@ PresentScreen(void)
     SDL20_RenderPresent(renderer);
     VideoSurfaceUpdatedInBackgroundThread = SDL_FALSE;
     VideoSurfaceLastPresentTicks = SDL20_GetTicks();
-    VideoSurfacePresentTicks = 0;
 
     UnlockVideoRenderer();
 }
```

**Comment by icculus** [comment]
Good sleuthing! I'll take a closer look at this soon.

**Comment by twolife** [comment]
@icculus no no no 😄 
#400 doesn't solve this (unfortunately)

**Comment by madebr** [comment]
The `fix #386` snippet in the text threw GitHub off :)

**Comment by icculus** [comment]
I just came here to reopen this, too, haha. Sorry, GitHub was overly-helpful this time!

**Comment by sulix** [comment]
I can confirm the patch above fixes both SimCity 3000's into cinematic and some more minor flickering in the cinematics in Civilization: Call to Power.

And, having thought about it a bit, I'm pretty certain this is the _correct_ fix to the problem (insofar as the YUV / present stuff is correct at all), not just a workaround. ``VideoSurfacePresentTicks`` is essentially our marker that there's an overlay which needs displaying, so we definitely should clear it as soon as we've committed to presenting it, otherwise we end up trying to render more overlay frames than exist.

So +1 from me for this going in as-is.

**Comment by Gymnasiast** [comment]
Played SimCity 3000 tonight (using @twolife ’s shims) and it ran without problems! Thanks to all involved! 👍
