### ISSUE TITLE
dosbox keyboard layout issues

### ISSUE THREAD

**Issue by sezero** [libsdl-org/sdl12-compat#84]
dosbox-0.74 on CentOS-6.10 / i686.

With 'normal' SDL-1.2, dosbox doesn't respect my keyboard layout (which
is Turkish-F) and behave as is I were using US layout.

With sdl12-compat (latest git master) talking to SDL2-latest git master,
it does use my keyboard layout but not fully correctly:

- The key next to left-shift should report `<`, `>` or `|` (plain, with
  shift, with AltGr) but it prints `\`, `|` or none: all behaving like
  US-layout.

- The key next to right shift should report `,` or `;` (plain or shift),
  but it prints `,` (which is good) or `<` (bad: US-layout).

- The key left to it should report `.` or `:`, but it prints `.` (good)
  or `>` (bad: US-layout).

- Similar stuff with the keys on the numbers' row -- e.g. the key below
  Esc prints nothing, ...

**Comment by sezero** [comment]
If it matters, here is the console output:
```
INFO: sdl12-compat, built on Jun  6 2021 at 19:44:55, talking to SDL2 2.0.15
DOSBox version 0.74
Copyright 2002-2010 DOSBox Team, published under GNU GPL.
---
INFO: FIXME: there is never a parachute in SDL2, should we catch segfaults ourselves? (SDL_Init:1578)
INFO: FIXME: support SDL_INIT_EVENTTHREAD where it makes sense? (SDL_InitSubSystem:1552)
CONFIG:Loading primary settings from config file /home/ozzie/.dosbox/dosbox-0.74.conf
INFO: FIXME: Should we offer scaling for windowed modes, too? (SDL_SetVideoMode:3594)
INFO: FIXME: currently ignores SDL_WINDOWID, which we could use with SDL_CreateWindowFrom ...? (SDL_SetVideoMode:3611)
INFO: FIXME: handle SDL_ANYFORMAT (SDL_SetVideoMode:3625)
INFO: FIXME: There's an environment variable to choose a display (SDL_SetVideoMode:3632)
INFO: FIXME: bgr instead of rgb? (SDL_SetVideoMode:3652)
INFO: FIXME: don't do anything if the window's dimensions, etc haven't changed. (SDL_SetVideoMode:3659)
INFO: FIXME: we need to preserve VideoSurface12 (but not its pixels), I think... (SDL_SetVideoMode:3660)
INFO: FIXME: setup screen saver (SDL_SetVideoMode:3899)
SDL:You are running in 24 bpp mode, this will slow down things!
INFO: FIXME: This should only save the dst rect in use (SaveDestAlpha:3927)
INFO: FIXME: write me (SDL_GetWMInfo:4774)
Memory sizes above 31 MB are NOT recommended.
Stick with the default values unless you are absolutely certain.
INFO: FIXME: Respect 1.2 environment variables for defining format here. (SDL_OpenAudio:5735)
ALSA:Can't subscribe to MIDI port (65:0) nor (17:0)
MIDI:Opened device:none
INFO: FIXME: bgr instead of rgb? (SDL_SetVideoMode:3653)
INFO: FIXME: Don't hardcode 15, do this based on display refresh rate. (SDL_UpdateRects:4412)
INFO: FIXME: Maybe just flip it immediately in PumpEvents if this flag is set, instead? (SDL_UpdateRects:4413)
INFO: FIXME: SDL1.2 and SDL2.0 scancodes are incompatible (EventFilter20to12:2507)
INFO: FIXME: SDL1.2 and SDL2.0 scancodes are incompatible (EventFilter20to12:2481)
```

**Comment by sulix** [comment]
Does this still appear if you set ``usescancodes = false`` in the ``dosbox.conf`` file (often in ``~/.dosbox/dosbox-0.74-3.conf`` or similar)?

If not, this is probably fallout from
```
INFO: FIXME: SDL1.2 and SDL2.0 scancodes are incompatible (EventFilter20to12:2507)
INFO: FIXME: SDL1.2 and SDL2.0 scancodes are incompatible (EventFilter20to12:2481)
```

Of course, DOSBox's ``usescancodes`` feature has been buggy even on real SDL 1.2, so I admittedly had it disabled anyway…

**Comment by sezero** [comment]
> Does this still appear if you set `usescancodes = false` in the `dosbox.conf` file

Doesn't fix the issue.

**Comment by DominusExult** [comment]
I'm having the same issue with the German keyboard layout. Seems there is some confusion between SDL12compat detecting the correct keyboard layout and DOSBox wanting to use the US layout. If I enter the correct keyboardlayout for Germany (enter "keyb gr" or "keyb us" to get back to US layout) I get *almost* the correct layout but some things are not working at all or correctly.

This is *probably* due to having to have disable "usescancodes" to get anything other than "a" when typing (thanks for pointing me at that in the other issue).
When I disable usescancodes on macOS and DOSBox + SDL 1.2x I get the same issues.
QWERTZ vs QWERTY for example: German keyboard layout is QWERTZ, without any keyb entry, DOSBox uses QWERTZ (correct), if I switch to German layout, I end up with QWERTY.
All keys not on the US keyboard don't work at all (üöäß...).
With usescancodes enabled this works correctly in DOSBox + SDL 1.2x.

When I hit one of the keys that do nothing at all I get:
```
INFO: FIXME: nothing maps to SDLK12_COMPOSE, SDLK12_BREAK, or SDLK12_EURO ...? (Keysym20to12:2334)
INFO: FIXME: map some of the SDLK12_WORLD keys (Keysym20to12:2335)
INFO: FIXME: SDL1.2 and SDL2.0 scancodes are incompatible (EventFilter20to12:2481)
```

**Comment by DominusExult** [comment]
A comment on DOSBox' irc channel:
> Given usescancodes' platform dependent nature, I'm not sure how easy it'll be to support it, other than hardcoding code tables for a few platforms and then translating SDL2 scancodes to these codes.

This probably sums it up nicely. AFAIU usescancodes never worked good on linux though otoh it worked on Windows and macOS. And seems to be really needed (at last on macOS) for non-US keyboards.
An unofficial SDL2 patch for DOSBox worked fine without it.

**Comment by sulix** [comment]
Okay, so what seems to be happening is this: the scancode field in SDL 1.2 is very platform dependent. DOSBox tries to make use of it, and has its own conversion tables from scancode to keys.

sdl12-compat hardcodes the scancode to 0 at the moment. DOSBox will fall back to using Keysyms instead, because 0 is an invalid scancode, except on Mac OS X, where 0 is valid, and refers to 'A'. This is why you were getting A on a Mac, but all the other platforms were working — efectively usescancode is always disabled for them.

Now, when usescancode is disabled, we have a different problem. SDL 1.2 ignores the keyboard layout for Keysyms, but SDL 2.0 doesn't (if you want to ignore the keyboard layout, you need to use SDL 2.0 scancodes, which are totally different from SDL 1.2 hardware-dependent scancodes). So what is probably happening is that on SDL 1.2, DOSBox is trying to do its own keyboard layout conversion, and this never fully worked without scancodes as some keys didn't have an SDLK_ value. In SDL 2.0, this is even worse, as we have both the OS and DOSBox trying to apply a keyboard layout (and often cancelling each other out, due to the way keys tend to be swapped).

The "correct" fix here is to, as mentioned, hardcode a conversion table from SDL2 Scancodes → SDL Scancodes per platform. It may also be more correct to convert from SDL2 Scancodes to SDLK_ keysyms, rather than using the SDL2 Keysyms.

DOSBox's code can be found [here](https://sourceforge.net/p/dosbox/code-0/HEAD/tree/dosbox/tags/RELEASE_0_74_3/src/gui/sdl_mapper.cpp#l308), including all of the conversion tables we'd need to support. Note the code has some tricky things like "Linux scancodes = Windows scancodes + 8" or similar through it.

I've started proof-of-concepting up the scancode conversion, and it seems to work okay with usescancodes=true, but I haven't finished filling in the tables, and it may not work as well on other platforms. (Again Mac OS X has quite different code here…)

The other useful thing to do would be to use the ``checkeys`` test app for any problematic keys, particularly if it gives different results under sdl12-compat and real SDL 1.2. (Though there are plenty of differences at the moment, which is part of the problem.)

**Comment by NY00123** [comment]
For reference, the unofficial DOSBox SDL 2.0 patch removes the option `usescancodes`. It basically migrates `sdl_mapper.cpp` to using SDL2 scancodes more-or-less exclusively, in place of keysyms.

Additionally, while SDL 1.2's `SDLK_LAST` doesn't exist in 2.0, SDL2 introduced `SDL_NUM_SCANCODES`, so an instance of `CKeyBindGroup` can simply be created with an array indexed by SDL 2.0 scancodes instead of SDL 1.2 keysyms.

**Comment by sulix** [comment]
Okay, I've written pull request #88 which should add some very basic support for scancodes so that ``usescancodes`` works. It turns out things were even more horrible than I thought, as the scancode mapping table also depends on what keyboard driver you're using under X11 — joy!

In any case, this should improve things with ``usescancodes=true``, but I've only tested it on Linux, and only really with a US keyboard layout. (I gave French AZERTY a quick go to check nothing exploded, but haven't tested it in detail.)

If a particular key's broken, the output of the ``checkkeys`` SDL 1.2 test program would help, especially if it differs between running under SDL 1.2 and sdl12-compat. But for it to be really useful, it's worth adjusting the ``PrintKey()`` function in it to print the scancode even when there is a valid keycode.

And, of course, do use the SDL 2.0 patch for DOSBox if you actually want something properly reliable, keyboard wise, because that sounds so much less terrible than the existing version's mess!

**Comment by NY00123** [comment]
I can add that for DOSBox 0.72, `usescancodes=true` broke under Linux/X11 with evdev. This was fixed in DOSBox 0.73, and it should explain the `evdev_input` check.

**Comment by sezero** [comment]
#88 made some improvements, but it still didn't fully fix this: dosbox
now seems to 'use' US-layout again even though I have Turkish-F layout,
but some keys still aren't correct. E.g. the 'e' key (the 3rd key from
`Tab`) doesn't print anything, `u` key (according to US-layout) prints
`r` instead (i.e. the Turkish-F layout), etc...

**Comment by sezero** [comment]
If it matters, this is my kbd layout: https://github.com/freedesktop/xkeyboard-config/blob/master/symbols/tr#L60

**Comment by sulix** [comment]
Okay: the issue with ``u`` was a simple mistake on my part: the scancode was missing from the commit in #88. Pull request #91 adds it back.

For ``e`` (which is ``ğ``, correct?), the problem is that there's no ``SDLK_ğ`` value, so it gets mapped to ``SDLK_UNKNOWN``. Since we discard all key events with a ``sym`` of ``SDLK_UNKNOWN``, the key can't be used. Pull request #92 lets keyboard events with ``SDLK_UNKNOWN`` through, and fixes the problem.

Of course, the underlying issue, which would've worked around the 'U' bug, and fixed the 'E' one, is that SDL 2.0's Keycodes use the values from the current keyboard layout but — on my machine, at least — SDL 1.2's Keycodes always use a US keyboard layout, regardless of what the user's OS is configured to use (like SDL 2.0's scancodes). The proper fix for that, then, is to use SDL 2.0 Scancodes everywhere in sdl12-compat, including converting them for the ``keysym.sym`` value, and to not use SDL 2.0 Keycodes at all.

In any case, with those changes, DOSBox seems pretty usable even if I set my Linux/X11 keyboard layout to Turkish F (though it behaved as US QWERTY from within DOSBox).

**Comment by sezero** [comment]
PRs #91 and #92 made my dosbox to behave thanks.

Should we keep this bug open?

**Comment by sulix** [comment]
There's still a difference in behaviour between SDL 1.2 and sdl12-compat if ``usescancodes=false``, which I'll try to fix in the next couple of days. There's no reason that couldn't be a separate issue though, if you'd prefer.

I wouldn't mind hearing from @DominusExult (or anyone else) to see if this works on Mac OS X (with ``usescancodes=true``) — the OS X codepath is quite different and totally untested. I haven't tried it on Windows either, though that's at least slightly more similar to the Linux path. Of course, if we wanted to close this issue, any bugs which exist on other platforms could be filed separately.

Personally, I think it's worth keeping this bug open a little longer just to keep all of these DOSBox keyboard things in one place if we can…

**Comment by sezero** [comment]
OK, let's keep this open for a while.

**Comment by DominusExult** [comment]
Much better now on macOS, thank you.

But with usescancodes=true something is wrong with the modifier keys:
left control prints: /
right control doesn't seem to work
right shift doesn't work
right option (alt) doesn't work
(left option+enter does correctly switch to fullscreen mode).

**Comment by sulix** [comment]
Thanks for testing!

Two new pull requests out:
#96 fixes the left control button on macOS — it was a typo in the scancode conversion, easily fixed.
#97 reworks the way the non-scancode path works to be indpendent of keyboard layout. This ought to fix the ``usescancodes=false`` case — at least getting it to behave the same way as the real SDL 1.2 does.

Maybe the second one will fix the right control, shift, option keys, maybe it won't. [DOSBox's code](https://sourceforge.net/p/dosbox/code-0/HEAD/tree/dosbox/tags/RELEASE_0_74_3/src/gui/sdl_mapper.cpp#l356) seems to imply that there aren't any scancodes for these on Mac OS X:
```
	/* 4 extra keys that don't really exist, but are needed for
	 * round-trip mapping (dosbox uses RMETA only for hotkeys, it's
	 * not really mapped to an emulated key) */
	SDLK_RMETA, SDLK_RSHIFT, SDLK_RALT, SDLK_RCTRL,
```

Maybe the non-scancode fallback being fixed in #97 will fix this, maybe it won't. (To be honest, unless you're using a non-standard keyboard layout where these are mapped elsewhere, I doubt this'd fix it.)

If you can run the SDL 1.2 ``checkkeys`` program and post what it prints out for those keys, that might help us work out what's going on. (Especially if you can patch it to always print scancodes out…) I'm not actually sure what it returns: maybe they just have the same scancode as their "left" counterparts, maybe they return an unknown scancode, and if so what one?

**Comment by DominusExult** [comment]
#96 is good!
#97 doesn't fix it the right meta keys :(

But probably important fact that I only hinted at:
the right meta keys only don't work in DOSBox with usescancodes=true. With false these work.

checkkeys SDL1.2 (right & left shift, ctrl, option/alt, cmd):
```
Key pressed:  303-right shift  modifiers: RSHIFT
Key released:  303-right shift  modifiers: (none)
Key pressed:  304-left shift  modifiers: LSHIFT
Key released:  304-left shift  modifiers: (none)
Key pressed:  305-right ctrl  modifiers: RCTRL
Key released:  305-right ctrl  modifiers: (none)
Key pressed:  306-left ctrl  modifiers: LCTRL
Key released:  306-left ctrl  modifiers: (none)
Key pressed:  307-right alt  modifiers: RALT
Key released:  307-right alt  modifiers: (none)
Key pressed:  308-left alt  modifiers: LALT
Key released:  308-left alt  modifiers: (none)
Key pressed:  309-right meta  modifiers: RMETA
Key released:  309-right meta  modifiers: (none)
Key pressed:  310-left meta  modifiers: LMETA
Key released:  310-left meta  modifiers: (none)
```

checkkeys SDL12-compat with #97 (left and right shift, ctrl, option/alt, cmd):
```
Key pressed:  303-right shift  modifiers: RSHIFT
Key released:  303-right shift  modifiers: (none)
Key pressed:  304-left shift  modifiers: LSHIFT
Key released:  304-left shift  modifiers: (none)
Key pressed:  305-right ctrl  modifiers: RCTRL
Key released:  305-right ctrl  modifiers: (none)
Key pressed:  306-left ctrl  modifiers: LCTRL
Key released:  306-left ctrl  modifiers: (none)
Key pressed:  307-right alt  modifiers: RALT
Key released:  307-right alt  modifiers: (none)
Key pressed:  308-left alt  modifiers: LALT
Key released:  308-left alt  modifiers: (none)
Key pressed:  312-right super  modifiers: RMETA
Key released:  312-right super  modifiers: (none)
Key pressed:  311-left super  modifiers: LMETA
Key released:  311-left super  modifiers: (none)
```
Note that the cmd key number is different between SDL 12.2 and SDL12compat!

and for completion's sake SDL2 checkkeys:
```
INFO: Key pressed :  scancode 229 = Right Shift, keycode 0x400000E5 = Right Shift  modifiers: RSHIFT
INFO: Key released:  scancode 229 = Right Shift, keycode 0x400000E5 = Right Shift  modifiers: (none)
INFO: Key pressed :  scancode 225 = Left Shift, keycode 0x400000E1 = Left Shift  modifiers: LSHIFT
INFO: Key released:  scancode 225 = Left Shift, keycode 0x400000E1 = Left Shift  modifiers: (none)
INFO: Key pressed :  scancode 224 = Left Ctrl, keycode 0x400000E0 = Left Ctrl  modifiers: LCTRL
INFO: Key released:  scancode 224 = Left Ctrl, keycode 0x400000E0 = Left Ctrl  modifiers: (none)
INFO: Key pressed :  scancode 228 = Right Ctrl, keycode 0x400000E4 = Right Ctrl  modifiers: RCTRL
INFO: Key released:  scancode 228 = Right Ctrl, keycode 0x400000E4 = Right Ctrl  modifiers: (none)
INFO: Key pressed :  scancode 226 = Left Option, keycode 0x400000E2 = Left Option  modifiers: LALT
INFO: Key released:  scancode 226 = Left Option, keycode 0x400000E2 = Left Option  modifiers: (none)
INFO: Key pressed :  scancode 230 = Right Option, keycode 0x400000E6 = Right Option  modifiers: RALT
INFO: Key released:  scancode 230 = Right Option, keycode 0x400000E6 = Right Option  modifiers: (none)
INFO: Key pressed :  scancode 227 = Left Command, keycode 0x400000E3 = Left Command  modifiers: LGUI
INFO: Key released:  scancode 227 = Left Command, keycode 0x400000E3 = Left Command  modifiers: (none)
INFO: Key pressed :  scancode 231 = Right Command, keycode 0x400000E7 = Right Command  modifiers: RGUI
INFO: Key released:  scancode 231 = Right Command, keycode 0x400000E7 = Right Command  modifiers: (none)
```

**Comment by sulix** [comment]
Thanks a bunch!

I found the scancode values for the Right Ctrl, Alt, Shift, and Meta (Command) keys, which were apparently added in OS X Panther, and DOSBox never updated itself to support them explicitly as scancodes. This is in PR #98, which hopefully will fix the issue when ``usescancodes=true``.

I also updated pull request #97 to map the SDL 2.0 {L,R}GUI scancodes as {L,R}META on macOS, which should match what SDL 1.2 does. Not sure if that will help DOSBox at all, but it should make ``checkkeys`` match.

Finally, pull request #99 updates ``checkkeys`` to always print the scancode. If things are still not working, that should help provide a bit more debugging info in case we're just outputting the wrong scancode. There are probably quite a few missing or incorrect on OS X, as I just ripped a few by hand from what DOSBox was doing, and clearly that was a bit dodgy, so feel free to report any others which cause problems. (Unknown keys currently act as having scancode ``0x34`` on OS X, which is almost certainly wrong, but hopefully shouldn't break DOSBox, which doesn't handle it.)

**Comment by DominusExult** [comment]
Does DOSBox need to be patched with the correct scancodes as well? Because these still don't do anything when I applied #98 (or even when I applied #97 and #98 on top of it).

**Comment by sulix** [comment]
Darn… I'd've hoped that'd've worked even without any patches to DOSBox. Certainly DOSBox probably should be patched to properly support those keys, but if it's working under real SDL 1.2 without a patch, we should be able to imitate whatever it does.

Does DOSBox distinguish between the left and right keys under the real SDL 1.2 for you? (You can use the DOSBox keymapper with Ctrl+F1, and then clicking on a key, then add, then pressing a key. There should then be something saying ``BIND: key right ctrl`` or similar in the bottom-left.

Also, if you can post the results of ``checkkeys`` with the patch in PR #99 applied, that should at least let us know what scancode SDL 1.2 is giving for those keys. If it's different, then we've probably found our bug. If it's the same, I'm not sure what we can do…

Finally, worst-case we can make the right-hand-side keys just behave as a second set of the left-hand-side ones. I'd rather not have to do that, but it might be necessary for MacOS apps which expect an OS < 10.3.0, as that's what SDL 1.2 does on those. Maybe DOSBox is like that?

**Comment by DominusExult** [comment]
In SDL 1.2 DOSBox the keymapper correctly recognizes the right modifier keys. With SDL12 compat it recognizes them as unknown keys.

Under SDL 1.2 the checkkeys does not print the scancodes for the modifiers (left and right), after applying the same changes to it as #99. Other than that the the source file is the same so there is something somewhere else in SDL 1.2 that prevents the scancodes being shown.

SDL 1.2:
`Key pressed:  305-right ctrl (scancode = 0 [0x0]) modifiers: RCTRL`

SDL12-compat:
`Key pressed:  305-right ctrl (scancode = 62 [0x3e]) modifiers: RCTRL`

I'm in contact with a DOSBox dev and will try how it works out when the scancodes are applied.

**Comment by sulix** [comment]
Okay — I think I've got it now:
- On macOS SDL 1.2, 0 is both "unknown" and the "a" key: it's not possible to distinguish between them from scancode alone.
- DOSBox checks the keysym if the scancode is 0 to make sure it's not a known printable character (i.e. "a"), then falls back to using the keysm.sym value.
- On macOS, the scancode for modifier keys is always set to 0: https://github.com/libsdl-org/SDL-1.2/blob/main/src/video/quartz/SDL_QuartzEvents.m#L475 — so we should never translate scancodes for Ctrl, Alt, Meta, etc.

This basically means that:
- #98 is wrong: the real SDL 1.2 doesn't support scancodes for those keys (even if, technically, they exist).
- In fact, because we disable some of them for Windows/Linux as well, we can simplify this quite a bit.
- The "unknown" key scancode in SDL 1.2 is 0, and everyone has just been working around the issues caused by that also being the correct scancode for "a". 
- I was using ``0x34`` to work around that, as I thought it was unused from a quick, incorrect reading of the DOSBox code. This actually just broke the fallback to a non-scancode-based path, which is what happens on SDL 1.2.

So, I'm going to abandon #98 (even if it's technically "more correct" than what the real SDL 1.2 does) and make the "unknown" scancode 0. That should be enough to get this working.

I'll also get rid of the scancodes for the left-hand-side modifiers. I think Caps-Lock also lacks one. DOSBox seems to actually assume these exist and work, but SDL 1.2 never seems to produce them, so for accuracy we probably shouldn't either.

**Comment by DominusExult** [comment]
Success!!! Thank you!

**Comment by sulix** [comment]
Excellent. I think we can call this issue fixed now, with all these fixes having been merged.

(I'm not sure if anyone's tested it on Windows yet, admittedly, but I guess we could open a new issue if there are any remaining issues.)

**Comment by sezero** [comment]
OK closing. Thanks.

**Comment by DominusExult** [comment]
I don't know if that problem was there right away with this fix or something changed since then but now with scancodes enabled, some keys are wrong:
key on keyboard = key printed in DOSBox
a = 9
n = k
m = ;

**Comment by sezero** [comment]
Which OS? What keyboard layout?

**Comment by DominusExult** [comment]
Sorry, macOS 11, German layout but DOSBox thinks by default it is the US one, but still does it wrong if I switch to the correct one with "keyb gr"

**Comment by sezero** [comment]
Re-opening: @sulix this is for you.

**Comment by DominusExult** [comment]
checkkeys results for a, n, m, 9, k, ö
```
Key pressed:  97-a (scancode = 25 [0x19]) (a) modifiers: (none)
Key released:  97-a (scancode = 25 [0x19]) modifiers: (none)
Key pressed:  110-n (scancode = 40 [0x28]) (n) modifiers: (none)
Key released:  110-n (scancode = 40 [0x28]) modifiers: (none)
Key pressed:  109-m (scancode = 41 [0x29]) (m) modifiers: (none)
Key released:  109-m (scancode = 41 [0x29]) modifiers: (none)
Key pressed:  57-9 (scancode = 25 [0x19]) (9) modifiers: (none)
Key released:  57-9 (scancode = 25 [0x19]) modifiers: (none)
Key pressed:  107-k (scancode = 40 [0x28]) (k) modifiers: (none)
Key released:  107-k (scancode = 40 [0x28]) modifiers: (none)
Key pressed:  59-); (scancode = 41 [0x29]) (?) modifiers: (none)
Key released:  59-); (scancode = 41 [0x29]) modifiers: (none)
```

**Comment by sulix** [comment]
Thanks. The checkkeys output seems to confirm my suspicion here — that it's just some incorrect entries in the conversion table — and PR #121 should fix it.

The scancode backend is different for every OS, so this looks like a macOS-specific issue. Indeed, I pulled the macOS scancodes from the DOSBox source, and there appear to have been some mistakes due to copy-paste errors on my part and a misleading comment on DOSBox's. Unfortunately, I have no macOS machine to test it on, so hopefully these new ones are correct.

Note that DOSBox is supposed to default to the US keyboard layout, and does it's own layout handling after getting US-layout scancodes/keycodes from SDL, so that is the expected behaviour (though it's definitely the case that the real SDL 1.2 and/or OS can incorrectly translate the keys itself in some circumstances).

**Comment by DominusExult** [comment]
Thanks a lot, these work! 
I found some other keys that are not ok:
lower row, left to y (German QWERTZ layout) there is
< (and > with shift) but they print out a (or A)
checkkeys:
```
Key pressed:  92-\ (scancode = 0 [0x0]) (<) modifiers: (none)
Key released:  92-\ (scancode = 0 [0x0]) modifiers: (none)
Key pressed:  303-right shift (scancode = 0 [0x0]) modifiers: RSHIFT
Key pressed:  92-\ (scancode = 0 [0x0]) (>) modifiers: RSHIFT
Key released:  92-\ (scancode = 0 [0x0]) modifiers: RSHIFT
Key released:  303-right shift (scancode = 0 [0x0]) modifiers: (none)
```

in the numpad the keys for `= * +` are not registering.
```
Key pressed:  272-equals (scancode = 81 [0x51]) (=) modifiers: (none)
Key released:  272-equals (scancode = 81 [0x51]) modifiers: (none)
Key pressed:  268-[*] (scancode = 66 [0x42]) (*) modifiers: (none)
Key released:  268-[*] (scancode = 66 [0x42]) modifiers: (none)
Key pressed:  270-[+] (scancode = 68 [0x44]) (+) modifiers: (none)
Key released:  270-[+] (scancode = 68 [0x44]) modifiers: (none)
```
in DOSBox with normal SDL 1.2x `+` and `*` work but `=` doesn't print as well.

**Comment by sulix** [comment]
Hmm… those ones are a little trickier:
The angle brackets seem to use a backslash keycode, so are probably implemented as NONUSBACKSLASH. At least DOSBox doesn't seem to have a separate scancode for that, so I could make it the same as the regular backslash scancode, but that might also give the wrong key.
The other option is that we shouldn't be treat its keycode as a BACKSLASH, but rather as something like one of the WORLD keys.

Can you run checkkeys against normal SDL 1.2 and try pressing those keys, so we can see what output it gives? If you can easily run the SDL 2.0 checkkeys as well, that'll give us both sides of what needs to be converted…

The keypad + and * were some off-by-one errors in the scancodes in the table. I'll fix those.

The keypad = really should work: the DOSBox code explicitly tries to handle it for macOS, and uses the same scancode, so I guess that's a bug deeper in the DOSBox code. My US-layout keyboard doesn't have a keypad =, so I wasn't able to test it under Linux.

**Comment by DominusExult** [comment]
I had edited my post above to say that this key `<` seems to not work correctly in SDL 1.2 DOSBox as well. Maybe a problem in SDL 1.2 or in DOSBox.

SDL 1.2 checkkeys:
```
Key pressed:  60-< (scancode = 50 [0x32]) (<) modifiers: (none)
Key released:  60-< (scancode = 50 [0x32]) modifiers: (none)
Key pressed:  303-right shift (scancode = 0 [0x0]) modifiers: RSHIFT
Key pressed:  60-< (scancode = 50 [0x32]) (>) modifiers: RSHIFT
Key released:  60-< (scancode = 50 [0x32]) modifiers: RSHIFT
Key released:  303-right shift (scancode = 0 [0x0]) modifiers: (none)
```

SDL 2 checkkeys:
```
INFO: Key pressed :  scancode 100 = , keycode 0x0000005E = ^  modifiers: (none)
INFO: INPUT Text (\x3c): "<"
INFO: Key released:  scancode 100 = , keycode 0x0000005E = ^  modifiers: (none)
INFO: Key pressed :  scancode 229 = Right Shift, keycode 0x400000E5 = Right Shift  modifiers: RSHIFT
INFO: Key pressed :  scancode 100 = , keycode 0x0000005E = ^  modifiers: RSHIFT
INFO: INPUT Text (\x3e): ">"
INFO: Key released:  scancode 100 = , keycode 0x0000005E = ^  modifiers: RSHIFT
INFO: Key released:  scancode 229 = Right Shift, keycode 0x400000E5 = Right Shift  modifiers: (none)
```

I'll investigate the = with the DOSbox devs. In all the years, I probably never needed to hit that key so I never noticed it is not working.

**Comment by sulix** [comment]
I've updated PR #121 which should fix all of these issues on macOS. I'm still not sure about the <> key on Linux/Windows — but I think I've got it as close to "right" as we can get it. (Though it could be buggy in DOSBox on Linux, where it doesn't seem to be handled properly.)
